FROM python:3.7.6

WORKDIR /src
ARG MDAI_PATH

--ENV--

COPY requirements.txt /src/requirements.txt
RUN pip install -r requirements.txt

COPY lib/requirements.txt /src/model-requirements.txt
RUN pip install -r model-requirements.txt

COPY lib/${MDAI_PATH}/requirements.txt /src/mdai-requirements.txt
RUN pip install -r mdai-requirements.txt

COPY server.py /src/
COPY validation.py /src/
ENV MDAI_PATH=${MDAI_PATH}

--COPY--

RUN useradd docker
USER docker

EXPOSE 6324

--COMMAND--
